{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.138.782.0 (24.11)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"map\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-IN",
    "cultures": [
      {
        "name": "en-IN",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-IN",
    "tables": [
      {
        "name": "map",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "PathID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bd230104-2407-4e19-adbc-a61942a1516f",
            "sourceColumn": "PathID",
            "summarizeBy": "none"
          },
          {
            "name": "Station Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ba0add41-8a47-4137-b9b8-a67d3112a149",
            "sourceColumn": "Station Name",
            "summarizeBy": "none"
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "42c6e2b6-0725-41a3-8bd8-9e316907be11",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b91193cf-b4e6-40cf-ab96-263f057cc425",
            "sourceColumn": "State",
            "summarizeBy": "none"
          },
          {
            "name": "Fuel Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f724c6af-fd25-42e9-bbfb-f75da3eb874b",
            "sourceColumn": "Fuel Type",
            "summarizeBy": "none"
          },
          {
            "name": "Latitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "81fd16bc-427d-4301-aa3d-88da35f6346d",
            "sourceColumn": "Latitude",
            "summarizeBy": "none"
          },
          {
            "name": "Longitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c3306621-86cb-4e0c-9f89-d6cf891676ba",
            "sourceColumn": "Longitude",
            "summarizeBy": "none"
          },
          {
            "name": "PointOrder",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "efb1b907-f76f-4166-97ce-1cb09baa8a4b",
            "sourceColumn": "PointOrder",
            "summarizeBy": "none"
          },
          {
            "name": "Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c280fe57-98c7-44c0-a4ba-fde5c80b09c9",
            "sourceColumn": "Description",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "dd845a4b-e7c4-45ea-8d98-05de7327d52a",
        "partitions": [
          {
            "name": "map",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\csepr_utwv3lm\\OneDrive\\Desktop\\powerbi\\excel workbook sample files\\fuelstations.xlsx\"), null, true),",
                "    map_Sheet = Source{[Item=\"map\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(map_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"PathID\", Int64.Type}, {\"Station Name\", type text}, {\"City\", type text}, {\"State\", type text}, {\"Fuel Type\", type text}, {\"Latitude\", type number}, {\"Longitude\", type number}, {\"PointOrder\", Int64.Type}, {\"Description\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}