table map
	lineageTag: dd845a4b-e7c4-45ea-8d98-05de7327d52a

	column PathID
		dataType: int64
		formatString: 0
		lineageTag: bd230104-2407-4e19-adbc-a61942a1516f
		summarizeBy: none
		sourceColumn: PathID

		annotation SummarizationSetBy = User

	column 'Station Name'
		dataType: string
		lineageTag: ba0add41-8a47-4137-b9b8-a67d3112a149
		summarizeBy: none
		sourceColumn: Station Name

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 42c6e2b6-0725-41a3-8bd8-9e316907be11
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: b91193cf-b4e6-40cf-ab96-263f057cc425
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Fuel Type'
		dataType: string
		lineageTag: f724c6af-fd25-42e9-bbfb-f75da3eb874b
		summarizeBy: none
		sourceColumn: Fuel Type

		annotation SummarizationSetBy = Automatic

	column Latitude
		dataType: double
		lineageTag: 81fd16bc-427d-4301-aa3d-88da35f6346d
		summarizeBy: none
		sourceColumn: Latitude

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Longitude
		dataType: double
		lineageTag: c3306621-86cb-4e0c-9f89-d6cf891676ba
		summarizeBy: none
		sourceColumn: Longitude

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PointOrder
		dataType: int64
		formatString: 0
		lineageTag: efb1b907-f76f-4166-97ce-1cb09baa8a4b
		summarizeBy: none
		sourceColumn: PointOrder

		annotation SummarizationSetBy = User

	column Description
		dataType: string
		lineageTag: c280fe57-98c7-44c0-a4ba-fde5c80b09c9
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	partition map = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\csepr_utwv3lm\OneDrive\Desktop\powerbi\excel workbook sample files\fuelstations.xlsx"), null, true),
				    map_Sheet = Source{[Item="map",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(map_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"PathID", Int64.Type}, {"Station Name", type text}, {"City", type text}, {"State", type text}, {"Fuel Type", type text}, {"Latitude", type number}, {"Longitude", type number}, {"PointOrder", Int64.Type}, {"Description", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

